# Generated by Django 5.0.4 on 2024-05-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.IntegerField(default=0)),
                ('search_count', models.IntegerField(default=0)),
                ('remain_count', models.IntegerField(default=10)),
                ('regist_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
